FROM twobombs/cudacluster:vulkan

# apt reqs
RUN dpkg --add-architecture i386 && wget -nc https://dl.winehq.org/wine-builds/Release.key && apt-key add Release.key && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 76F1A20FF987672F && apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/ && apt-get update

# install wine32 wine64 steam lutris
RUN export DEBIAN_FRONTEND=noninteractive && add-apt-repository ppa:lutris-team/lutris && apt-get -y -f install libtasn1-bin && apt-get install libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 libsqlite3-0:i386 && apt-get update && apt-get install --install-recommends -y winehq-stable steam && apt clean all && apt -y autoremove
RUN export DEBIAN_FRONTEND=noninteractive && apt update && apt -y install lutris && apt clean all && apt -y autoremove

# install moonlight host
RUN apt install libboost-all-dev ffmpeg libssl-dev libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libopus-dev libx11-dev libpulse-dev && apt clean all
RUN git clone --recurse-submodules https://github.com/SunshineStream/Sunshine.git && cd Sunshine && cmake . && make 

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

EXPOSE 6080

ENTRYPOINT /root/run
