FROM twobombs/cudacluster:vulkan

# NV & Mesa samples building
RUN git clone https://github.com/NVIDIA/cuda-samples.git && cd cuda-samples && make
RUN apt-get install libgl1-mesa-dev freeglut3-dev libglew-dev cmake build-essential && apt clean all
RUN git clone https://github.com/freedesktop/mesa-demos.git && cd mesa-demos && cmake . && make && make install 

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

EXPOSE 6080

ENTRYPOINT /root/run
