FROM twobombs/cudacluster:vulkan

# libs
RUN apt update && apt-get install libgl1-mesa-dev freeglut3-dev libglew-dev cmake build-essential && apt clean all
# NV, OCL & Mesa samples building
RUN git clone -b 'v11.5' --single-branch --depth 1 https://github.com/NVIDIA/cuda-samples.git && cd cuda-samples && make -k -i -j2 2> /dev/null

#
RUN git clone https://github.com/twobombs/cuda-workshop.git && cd cuda-workshop && cd shrutil && cmake . && make shrutil
COPY oclSamples.tar.gz /oclSamples.tar.gz
RUN tar -xf oclSamples.tar.gz

#
# RUN git clone https://gitlab.freedesktop.org/mesa/demos.git && cd demos && cmake . && make -k -i -j2 && make install 

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

EXPOSE 6080

ENTRYPOINT /root/run
